baseURL = "http://example.org/"
languageCode = "fr-FR"
title = "Connards Confits - Tables Ephémères"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Des amis, des repas, du vin, du plaisir"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/cooking-knives.jpg"
  recent_posts_number = 2
